import Head from 'next/head';

interface AppHeadTitleProps {
  title?: string;
}

export function AppHeadTitle({ title = 'Create Next App' }: AppHeadTitleProps): JSX.Element {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
